/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author pablo
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {        
        JFrame rootWindowComponent = (JFrame)SwingUtilities.getRoot(this);
        final DialogLogin loginDialog = new  DialogLogin(rootWindowComponent, true);
        loginDialog.pack();
        loginDialog.setVisible(true);
        initComponents();
        
        SetAdminUIComponents();        
    }

    private void SetAdminUIComponents() {
        if (!IsAdmin()) {
            tpMainPanel.remove(pUsers);
            tpMainPanel.remove(pActivity);
            tpMainPanel.remove(pActivityType);
            tpMainPanel.remove(pEmails);
        }
    }

    private boolean IsAdmin() {
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        tpMainPanel = new javax.swing.JTabbedPane();
        pScoreboard = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pUsers = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        panelUsersAdd1 = new Presentation.PanelUsersAdd();
        panelUsersEdit1 = new Presentation.PanelUsersEdit();
        pActivity = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        panelActivityAdd1 = new Presentation.PanelActivityAdd();
        jPanel12 = new javax.swing.JPanel();
        panelActivityAdd3 = new Presentation.PanelActivityAdd();
        panelActivityEdit1 = new Presentation.PanelActivityEdit();
        panelActivityEdit2 = new Presentation.PanelActivityEdit();
        pActivityType = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        panelActivityTypeAdd2 = new Presentation.PanelActivityTypeAdd();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        panelActivityTypeEdit1 = new Presentation.PanelActivityTypeEdit();
        pEmails = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        panelEmailsEdit1 = new Presentation.PanelEmailsEdit();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tech Points");

        tpMainPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        pScoreboard.setLayout(new java.awt.BorderLayout());
        pScoreboard.add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        tpMainPanel.addTab("Scoreboard", pScoreboard);

        jTabbedPane3.addTab("Add", panelUsersAdd1);
        jTabbedPane3.addTab("Edit", panelUsersEdit1);

        javax.swing.GroupLayout pUsersLayout = new javax.swing.GroupLayout(pUsers);
        pUsers.setLayout(pUsersLayout);
        pUsersLayout.setHorizontalGroup(
            pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE))
        );
        pUsersLayout.setVerticalGroup(
            pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );

        tpMainPanel.addTab("Users", pUsers);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(panelActivityAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(panelActivityAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelActivityAdd1Layout = new javax.swing.GroupLayout(panelActivityAdd1);
        panelActivityAdd1.setLayout(panelActivityAdd1Layout);
        panelActivityAdd1Layout.setHorizontalGroup(
            panelActivityAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActivityAdd1Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 455, Short.MAX_VALUE))
        );
        panelActivityAdd1Layout.setVerticalGroup(
            panelActivityAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActivityAdd1Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Add", panelActivityAdd1);

        javax.swing.GroupLayout panelActivityEdit1Layout = new javax.swing.GroupLayout(panelActivityEdit1);
        panelActivityEdit1.setLayout(panelActivityEdit1Layout);
        panelActivityEdit1Layout.setHorizontalGroup(
            panelActivityEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActivityEdit1Layout.createSequentialGroup()
                .addComponent(panelActivityEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelActivityEdit1Layout.setVerticalGroup(
            panelActivityEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActivityEdit1Layout.createSequentialGroup()
                .addComponent(panelActivityEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Edit", panelActivityEdit1);

        javax.swing.GroupLayout pActivityLayout = new javax.swing.GroupLayout(pActivity);
        pActivity.setLayout(pActivityLayout);
        pActivityLayout.setHorizontalGroup(
            pActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4))
        );
        pActivityLayout.setVerticalGroup(
            pActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpMainPanel.addTab("Activity", pActivity);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(panelActivityTypeAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -20, -1, -1));

        jTabbedPane5.addTab("Add", jPanel6);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(panelActivityTypeEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 474, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(panelActivityTypeEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Edit", jPanel11);

        javax.swing.GroupLayout pActivityTypeLayout = new javax.swing.GroupLayout(pActivityType);
        pActivityType.setLayout(pActivityTypeLayout);
        pActivityTypeLayout.setHorizontalGroup(
            pActivityTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActivityTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE))
        );
        pActivityTypeLayout.setVerticalGroup(
            pActivityTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActivityTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpMainPanel.addTab("Activity Type", pActivityType);

        jTabbedPane6.addTab("Edit", panelEmailsEdit1);

        javax.swing.GroupLayout pEmailsLayout = new javax.swing.GroupLayout(pEmails);
        pEmails.setLayout(pEmailsLayout);
        pEmailsLayout.setHorizontalGroup(
            pEmailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE))
        );
        pEmailsLayout.setVerticalGroup(
            pEmailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpMainPanel.addTab("Emails", pEmails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(tpMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 631, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JPanel pActivity;
    private javax.swing.JPanel pActivityType;
    private javax.swing.JPanel pEmails;
    private javax.swing.JPanel pScoreboard;
    private javax.swing.JPanel pUsers;
    private Presentation.PanelActivityAdd panelActivityAdd1;
    private Presentation.PanelActivityAdd panelActivityAdd3;
    private Presentation.PanelActivityEdit panelActivityEdit1;
    private Presentation.PanelActivityEdit panelActivityEdit2;
    private Presentation.PanelActivityTypeAdd panelActivityTypeAdd2;
    private Presentation.PanelActivityTypeEdit panelActivityTypeEdit1;
    private Presentation.PanelEmailsEdit panelEmailsEdit1;
    private Presentation.PanelUsersAdd panelUsersAdd1;
    private Presentation.PanelUsersEdit panelUsersEdit1;
    private javax.swing.JTabbedPane tpMainPanel;
    // End of variables declaration//GEN-END:variables
}
