/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.ScoreBoard;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author pablo
 */
public class PanelScoreboardAllTime extends javax.swing.JPanel {

    /**
     * Creates new form PanelScoreboardAllTime
     */
    public PanelScoreboardAllTime() throws SQLException, ClassNotFoundException {
        initComponents();
        TableList();
        
      
        
    }

    private void TableList() throws SQLException, ClassNotFoundException {

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Name");
        model.addColumn("Points");
        model.addColumn("Position");
        
        ScoreBoard SB = new ScoreBoard();

        ArrayList<ScoreBoard> Table = SB.ShowTable();
         
        for (int x = 0; x < Table.size(); x++) {
            ScoreBoard a = Table.get(x);
            
            model.addRow(new Object[]{
                a.getFullname(),
                a.getPoints(),
                a.getIdScore()
            });
        }

        tblScore.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblScore = new javax.swing.JTable();

        tblScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Points", "Position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblScore);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblScore;
    // End of variables declaration//GEN-END:variables

}
