/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.Activity;
import Business.ScoreBoard;
import Business.User;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author TZ
 */
public class PanelActivityScoreBoard extends javax.swing.JPanel {

    /**
     * Creates new form PanelActivityScoreBoard
     */
     private ArrayList<Integer> listUsers = new ArrayList<>();
    private ArrayList<Integer> listActivity = new ArrayList<>();
    
    public PanelActivityScoreBoard() {
         try {
             initComponents();
             LoadUsers();
             LoadActivity();
         } catch (SQLException | ClassNotFoundException ex) {
             Logger.getLogger(PanelActivityScoreBoard.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    private void LoadUsers() throws SQLException, ClassNotFoundException {
        User u = new User();
        ArrayList<User> allUsers = u.List();
        listUsers.add(0);
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("--Seleccione--");

        for (int i = 0; i < allUsers.size(); i++) {
            listModel.addElement(allUsers.get(i).getUserName());
            listUsers.add(allUsers.get(i).getUserID());
        }

        tblUsers.setModel(listModel);
    }
    
        private void LoadUserSelected() {
        User u = new User();
        int selectedId = listUsers.get(tblUsers.getSelectedIndex());
        u.setUserID(selectedId);
        u.Find();
        txtUsers.setText(u.getUserName());
        txtUsers.setEnabled(false);

    }
    
        private void LoadActivity() throws SQLException, ClassNotFoundException {
        Activity a = new Activity();
        ArrayList<Activity> allActivity = a.List();
        listActivity.add(0);
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("--Seleccione--");

        for (int i = 0; i < allActivity.size(); i++) {
            listModel.addElement(allActivity.get(i).getName());
            listActivity.add(allActivity.get(i).getIdActivity());
        }

        tblActivity.setModel(listModel);
    }
    
        
        private void LoadSelectedActivity() {
        Activity u = new Activity();
        int selectedId = listActivity.get(tblActivity.getSelectedIndex());
        u.setIdActivity(selectedId);
        u.Find();
        txtActivity.setText(u.getName());
        txtActivity.setEnabled(false);

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblActivity = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtUsers = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtActivity = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        tblActivity.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblActivity.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tblActivityValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tblActivity);

        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tblUsersValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsers);

        jLabel1.setText("Find Activity");

        jLabel2.setText("Find Users");

        btnAssign.setText("Assign ");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(txtUsers);

        jScrollPane4.setViewportView(txtActivity);

        jLabel3.setText("User:");

        jLabel4.setText("Activity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(jScrollPane4)
                        .addComponent(btnAssign))
                    .addComponent(jLabel4))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAssign)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblActivityValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tblActivityValueChanged
        LoadSelectedActivity();

        /*activity.Find();
        cbActivityTypes.setSelectedIndex(activity.getIdActivityType());

        txtName.setText(activity.getName());
        txtDescrition.setText(activity.getDescription());
        txtPoints.setText(String.valueOf(activity.getPoints()));
        */
    }//GEN-LAST:event_tblActivityValueChanged

    private void tblUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tblUsersValueChanged
        LoadUserSelected();
    }//GEN-LAST:event_tblUsersValueChanged

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        User u = new User();
        int selectedId = listUsers.get(tblUsers.getSelectedIndex());
        u.setUserID(selectedId);
        //u.Find();
        Activity a = new Activity();
        int selectedIdA = listActivity.get(tblActivity.getSelectedIndex());
        a.setIdActivity(selectedIdA);
        a.Find();
        ScoreBoard s = new ScoreBoard(u, a); 
         try {
             s.Create();
             JOptionPane.showMessageDialog(null, "Correctly applied");
        
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(PanelActivityScoreBoard.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(PanelActivityScoreBoard.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> tblActivity;
    private javax.swing.JList<String> tblUsers;
    private javax.swing.JTextPane txtActivity;
    private javax.swing.JTextPane txtUsers;
    // End of variables declaration//GEN-END:variables
}
