/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.ActivityType;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pablo
 */
public class PanelActivityTypeAdd extends javax.swing.JPanel {

    /**
     * Creates new form PanelActivityTypeAdd
     */
    public PanelActivityTypeAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtActivityTypeName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtActivityTypeDefaultPoints = new javax.swing.JTextField();
        btmActivityTypeSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtActivityTypeDescription = new javax.swing.JTextArea();

        jLabel3.setText("Name");

        jLabel1.setText("Description:");

        jLabel4.setText("Default points:");

        txtActivityTypeDefaultPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActivityTypeDefaultPointsActionPerformed(evt);
            }
        });

        btmActivityTypeSave.setText("Save");
        btmActivityTypeSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmActivityTypeSaveActionPerformed(evt);
            }
        });

        txtActivityTypeDescription.setColumns(20);
        txtActivityTypeDescription.setRows(5);
        txtActivityTypeDescription.setText("Long description of the activity");
        jScrollPane1.setViewportView(txtActivityTypeDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btmActivityTypeSave)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtActivityTypeName)
                                    .addComponent(txtActivityTypeDefaultPoints)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtActivityTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtActivityTypeDefaultPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btmActivityTypeSave)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtActivityTypeDefaultPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActivityTypeDefaultPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActivityTypeDefaultPointsActionPerformed

    private void btmActivityTypeSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmActivityTypeSaveActionPerformed
        Save();
        
    }//GEN-LAST:event_btmActivityTypeSaveActionPerformed

    private void Save() throws NumberFormatException {
        try {
            // TODO add your handling code here:
            ActivityType at = new ActivityType();
            at.setName(txtActivityTypeName.getText());
            at.setDescription(txtActivityTypeDescription.getText());
            at.setPoints(Integer.parseInt(txtActivityTypeDefaultPoints.getText()));
            at.Create();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PanelActivityTypeAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmActivityTypeSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtActivityTypeDefaultPoints;
    private javax.swing.JTextArea txtActivityTypeDescription;
    private javax.swing.JTextField txtActivityTypeName;
    // End of variables declaration//GEN-END:variables
}
