/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.ScoreBoard;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pablo
 */
public class PanelScoreboardCurrentYear extends javax.swing.JPanel {

    /**
     * Creates new form PanelScoreboardCurrentYear
     */
    public PanelScoreboardCurrentYear() {
        try {
            initComponents();
            TableList();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(PanelScoreboardCurrentYear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     private void TableList() throws SQLException, ClassNotFoundException {

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Name");
        model.addColumn("Points");
        model.addColumn("Position");
        
        ScoreBoard SB = new ScoreBoard();

        ArrayList<ScoreBoard> Table = SB.ShowTableCurrentYear();
         
        for (int x = 0; x < Table.size(); x++) {
            ScoreBoard a = Table.get(x);
            
            model.addRow(new Object[]{
                a.getFullname(),
                a.getPoints(),
                a.getIdScore()
            });
        }

        tblCurrentYear.setModel(model);
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblCurrentYear = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tblCurrentYear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Points", "Position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCurrentYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCurrentYearMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCurrentYear);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblCurrentYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCurrentYearMouseClicked
        try {
            TableList();
        } catch (SQLException ex) {
            Logger.getLogger(PanelScoreboardCurrentYear.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelScoreboardCurrentYear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblCurrentYearMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCurrentYear;
    // End of variables declaration//GEN-END:variables
}
