/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.Activity;
import Business.ActivityType;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class PanelActivityAdd extends javax.swing.JPanel {

    private ArrayList<ActivityType> activityTypes;
    private ArrayList<Integer> activityTypesIds;
    
    
    /**
     * Creates new form PanelActivityAdd
     */
    public PanelActivityAdd() {
        initComponents();
        LoadActivityTypes();
    }
    
    private void LoadActivityTypes()
    {
        try {
            ActivityType activityType = new ActivityType();
            activityTypes =  activityType.List();
            activityTypesIds = new ArrayList<>();
            
            cbActivityTypes.addItem("-- Select Activity--");
            activityTypesIds.add(0);
            
            for (int i = 0; i < activityTypes.size(); i++)
            {
                cbActivityTypes.addItem(activityTypes.get(i).getName());
                activityTypesIds.add(activityTypes.get(i).getIdActivityType());
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PanelActivityAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbActivityTypes = new javax.swing.JComboBox<>();
        txtActivityName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtPoints = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        jLabel1.setText("Type:");

        jLabel2.setText("Name:");

        cbActivityTypes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbActivityTypesItemStateChanged(evt);
            }
        });
        cbActivityTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActivityTypesActionPerformed(evt);
            }
        });

        jLabel5.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setText("Long description of the activity");
        jScrollPane1.setViewportView(txtDescription);

        txtPoints.setText("0");

        jLabel6.setText("Points:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPoints)
                            .addComponent(cbActivityTypes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtActivityName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbActivityTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtActivityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        try {
            AddActivity();
        } catch (ClassNotFoundException | SQLException | NumberFormatException ex) {
            Logger.getLogger(PanelActivityAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void AddActivity() throws ClassNotFoundException, SQLException, NumberFormatException {
        
        int selectedActivityType = cbActivityTypes.getSelectedIndex();
        
        if (selectedActivityType > 0){
            int activityTypeId = activityTypesIds.get(selectedActivityType);
            ActivityType ac = new ActivityType();
            ac.setIdActivityType(activityTypeId);
            ac.Find();
            
            Activity activity = new Activity();
            activity.setIdActivityType(ac.getIdActivityType());
            activity.setName(txtActivityName.getText());
            activity.setDescription(txtDescription.getText());
            activity.setPoints(Integer.parseInt(txtPoints.getText()));        
            activity.Create();
            JOptionPane.showMessageDialog(null, "Activity added");
        
          
        }
        
        
        
    }

    private void cbActivityTypesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbActivityTypesItemStateChanged
        LoadDefaultPoints();
    }//GEN-LAST:event_cbActivityTypesItemStateChanged

    private void cbActivityTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActivityTypesActionPerformed
       
    }//GEN-LAST:event_cbActivityTypesActionPerformed

    private void LoadDefaultPoints() {
        int selectedActivityType = cbActivityTypes.getSelectedIndex();
        
        if (selectedActivityType > 0){
            int activityTypeId = activityTypesIds.get(selectedActivityType);
            ActivityType ac = new ActivityType();
            ac.setIdActivityType(activityTypeId);
            ac.Find();
            txtPoints.setText(String.valueOf(ac.getPoints()));
        }
        else
        {
            txtPoints.setText("0");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbActivityTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtActivityName;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtPoints;
    // End of variables declaration//GEN-END:variables
}
