/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class PanelUsersAdd extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsersAdd
     */
    public PanelUsersAdd() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnImage = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel3.setText("Full name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel4.setText("Email:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, 171, -1));
        add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 42, 171, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 79, 171, -1));

        btnImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnImage.setText("Imagen de perfil");
        btnImage.setBorder(new javax.swing.border.MatteBorder(null));
        add(btnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 90, 90));

        btnUpload.setText("Upload");
        add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
        User u = new User();
        u.setUserName(txtUserName.getText());
        u.setFullName(txtFullName.getText());
        u.setEmail(txtEmail.getText());  
        u.setPassword(txtpassword.getText());
        u.setStatus(true);
        try {
            u.Create();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelUsersAdd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Username already exists");
            String error = ex.getMessage();
            Logger.getLogger(PanelUsersAdd.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
