/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.ActivityType;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;

/**
 *
 * @author pablo
 */
public class PanelActivityTypeEdit extends javax.swing.JPanel {

    private ArrayList<Integer> listActivityTypes = new ArrayList<>();
    
    /**
     * Creates new form PanelActivityTypeEdit
     */
    public PanelActivityTypeEdit() {
        initComponents();
        try {
            LoadActivityTypes();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(PanelActivityTypeEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void LoadActivityTypes() throws SQLException, ClassNotFoundException {
        ActivityType at = new ActivityType();
        ArrayList<ActivityType> allActivityTypes = at.List();
        
        listActivityTypes.add(0);
        
        DefaultListModel listModel = new DefaultListModel();
        
        listModel.addElement("--Seleccione--");
        
        for (int i = 0; i < allActivityTypes.size(); i++) {
             listModel.addElement(allActivityTypes.get(i).getName());            
            listActivityTypes.add(allActivityTypes.get(i).getIdActivityType());
        }
        
        lstActivityTypes.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstActivityTypes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtActivityTypeName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtActivityTypeDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtActivityTypeDefaultPoints = new javax.swing.JTextField();
        btmActivityTypeSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        lstActivityTypes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstActivityTypes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstActivityTypesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstActivityTypes);

        jLabel1.setText("Name:");

        jLabel2.setText("Description:");

        txtActivityTypeDescription.setColumns(20);
        txtActivityTypeDescription.setRows(5);
        txtActivityTypeDescription.setText("Long description of the activity");
        jScrollPane2.setViewportView(txtActivityTypeDescription);

        jLabel3.setText("Default points:");

        btmActivityTypeSave.setText("Save");
        btmActivityTypeSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmActivityTypeSaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Find Activity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtActivityTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtActivityTypeDefaultPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btmActivityTypeSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtActivityTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtActivityTypeDefaultPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(btmActivityTypeSave)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstActivityTypesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstActivityTypesValueChanged
        LoadActivityType();
        
    }//GEN-LAST:event_lstActivityTypesValueChanged

    private void LoadActivityType() {
        ActivityType at = new ActivityType();
        int selectedId = listActivityTypes.get(lstActivityTypes.getSelectedIndex());
        at.setIdActivityType(selectedId);
        at.Find();
        txtActivityTypeName.setText(at.getName());
        txtActivityTypeDescription.setText(at.getDescription());
        txtActivityTypeDefaultPoints.setText(String.valueOf(at.getPoints()));
    }

    private void btmActivityTypeSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmActivityTypeSaveActionPerformed
        Edit();
    }//GEN-LAST:event_btmActivityTypeSaveActionPerformed

    private void Edit() {
        try {            
            int selectedId = listActivityTypes.get(lstActivityTypes.getSelectedIndex());
            ActivityType at = new ActivityType();            
            at.setIdActivityType(selectedId);
            at.setName(txtActivityTypeName.getText());
            at.setDescription(txtActivityTypeDescription.getText());
            at.setPoints(Integer.parseInt(txtActivityTypeDefaultPoints.getText()));
            at.Edit();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PanelActivityTypeAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmActivityTypeSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstActivityTypes;
    private javax.swing.JTextField txtActivityTypeDefaultPoints;
    private javax.swing.JTextArea txtActivityTypeDescription;
    private javax.swing.JTextField txtActivityTypeName;
    // End of variables declaration//GEN-END:variables
}
